### ISSUE TITLE
Namespace hardcoded in the chart

### ISSUE THREAD

**Issue by Tommy-Dimitrio** [Mirantis/metal3-helm-chart#10]
the namespace shouldn't be hardcoded in the chart even if passed in the values.

**Comment by stbenjam** [comment]
It looks like the namespace is configurable to me, see https://github.com/metal3-io/metal3-helm-chart/commit/d7a0ef2b37d8ceaa659d873c96340a5831679c0a

Is this not working?

**Comment by stbenjam** [comment]
Please feel free to re-open with more details about the problem, but closing this for now.

/close
